export default {
	POST_RECIEVED: 'POST_RECIEVED',
	CURRENT_LOCATION_CHANGED: 'CURRENT_LOCATION_CHANGED',
	POST_CREATED: 'POST_CREATED',
	CURRENT_USER_RECIEVED: 'CURRENT_USER_RECIEVED',
	USER_LOGOUT: 'USER_LOGOUT'
}